name: cicd

on:
  push:
    paths:
      - src/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      
      - name: shorten commit id
        shell: bash
        run: | 
           echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jonehb11/python-app:${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - name: Install argocd
        shell: bash
        run: |
           curl -ksSL -o https://argocd-server.argocd/download/argocd-linux-amd64
           chmod +x argocd
           sudo mv ./argocd /usr/local/bin/argocd
      - name: Argocd app sync
        shell: bash
        run: | 
          argocd login argocd.test.com \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app          