name: cicd

on:
  push:
    paths:
      - src/**

jobs:
  ci:
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
    runs-on: ubuntu-latest
    steps: 
      
      - name: shorten commit id
        shell: bash
        run: | 
           echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jonehb11/python-app:${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3


      - name: modify values file
        shell: bash
        run: |
           echo  ${{needs.ci.outputs.commit_id}}
           pip install yq
           yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' /charts/argocd/python-app/values.yaml
      - name: Install argocd
        shell: bash
        run: |
           curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64          
           chmod +x argocd-linux-amd64         
           sudo mv ./argocd-linux-amd64 /usr/local/bin/argocd
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'updates rto values .yaml'
          

      - name: Argocd app sync
        shell: bash
        run: | 
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app          